Adding better social volume query generation
santiment/sanbase2 pull request #2613
Opened 2021-03-19 13:33 UTC by spiderjako

## Changes

## Ticket

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have tried to find clearer solution before commenting hard-to-understand parts of code
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-03-19 13:41 UTC, IvanIvanoff commented on lib/sanbase_web/graphql/dataloader/postgres_dataloader.ex
> +          List.delete(all_projects, project)
This is very slow - on every iteration you delete a item from a list (linear operation), so the complexity is O(n,m) which in case of all projects is just n^2

2021-03-19 13:47 UTC, IvanIvanoff commented on lib/sanbase_web/graphql/dataloader/postgres_dataloader.ex
> +      Enum.any?([other_ticker, other_name, other_slug], fn element -> project_name =~ element end)
This is not equivalent to the sangraphs implementation.

You need to break the name by intervals or `-` and check for full matches of the resulted tokens.
With this implementation if there is a name `time`, then `"time" =~ "santiment"` is true as it looks for all substrings.

2021-03-19 15:04 UTC, IvanIvanoff commented on lib/sanbase_web/graphql/dataloader/postgres_dataloader.ex
> +      fn project ->
This implementation is ignoring the predefined custom queries.

This should be reworked like this:
```suggestion
    all_projects = Project.List.projects(preload: [:social_volume_query])
    
    Map.new(
      projects,
      fn
         %{social_volume_query: %{query: query}} -> query
         project ->       
```

2021-03-23 13:22 UTC, IvanIvanoff commented
This implementation will only expose this new social volume query in the API - it is not going to use it.
When sanbase makes a request to metricshub it uses [this function](https://github.com/santiment/sanbase2/blob/master/lib/sanbase/social_data/social_helper.ex#L13-L27) which will still generate the old social volume query.

2021-03-24 14:00 UTC, IvanIvanoff commented on lib/sanbase/social_data/social_helper.ex
> +    {:ok, slug}
This changes the semantics of the function now. It still has this clause:
```elixir
 def social_metrics_selector_handler(%{text: search_text}) do
    {:ok, search_text}
  end
  ```
  
So, now you don't know if the returned result is a slug or a text and in both cases you provide it to the `slug` argument in the request - this breaks the social volume by random text queries now.

2021-03-24 15:05 UTC, IvanIvanoff commented on lib/sanbase_web/graphql/dataloader/postgres_dataloader.ex
> +          query = SocialVolumeQuery.default_query(project)
I think we can rework the default query a little bit to avoid things like `theta OR theta ...`. You can plug both `Enum.map(&String.downcase/1)` and `Enum.uniq` in the pipeline there (if casing does matter, which is the case I think)

2021-03-24 15:23 UTC, spiderjako commented on lib/sanbase_web/graphql/dataloader/postgres_dataloader.ex
> +          query = SocialVolumeQuery.default_query(project)
``(if casing does matter, which is the case I think)`` in this case, should I or should I not add the .downcase?

2021-04-05 13:24 UTC, IvanIvanoff commented on lib/sanbase/social_data/social_helper.ex
> +    {:ok, %{slug: slug}}
Can you put a comment why we do this and what are the consequences?
A few points:
- We let metricshub ask sanbase back for the social volume query
- This is done so the social volume query that requires fetching all projects is needed.
- This will leverage the caching, so it won't be that slow.

2021-04-05 13:27 UTC, IvanIvanoff commented on lib/sanbase_web/graphql/dataloader/postgres_dataloader.ex
> +      )
```suggestion
    current_projects =  Enum.filter(all_projects, &1.id in projects_ids)
```

2021-04-05 13:39 UTC, IvanIvanoff commented on lib/sanbase_web/graphql/dataloader/postgres_dataloader.ex
> +      other_project_names = String.split(String.downcase(other_name), [" ", "-"])
Pipes > nesting. It should be other_name |> String.downcase() |> String.split([" ", "-"])

2021-04-05 15:28 UTC, IvanIvanoff commented on lib/sanbase_web/graphql/dataloader/postgres_dataloader.ex
> +          end
let's extract this in a separate function as the nesting becomes too big

2021-04-05 15:29 UTC, IvanIvanoff commented on lib/sanbase_web/graphql/schema/types/project_types.ex
> -
Why do you remove the field on the project type? This will break all existing clients - the frontend, metricshub, etc.

2021-04-05 15:29 UTC, IvanIvanoff requested changes
Undo the removed project API field

2021-04-06 13:17 UTC, IvanIvanoff approved these changes

2021-04-07 10:42 UTC, merged